library(statsr)
library(dplyr)
library(ggplot2)
fbf = read.csv("my_fb_friends.csv")
fbf$more_than_1_person_in_picture <- ifelse(fbf$people_in_pic>1, 
                               c("yes"), c("no")) 
#inference(y = friends, x = more_than_1_person_in_picture, data = fbf, statistic = "mean", type = "ht", null = 0, alternative = "twosided", method = "theoretical")
#inference(y = friends, x = gender, data = fbf, statistic = "mean", type = "ht", null = 0, alternative = "twosided", method = "theoretical")
#inference(y = more_than_1_person_in_picture, x=gender, data = fbf, statistic = "proportion", type = "ci", method = "theoretical", success = "yes")
#ggplot(data = fbf, aes(x = people_in_pic)) + geom_histogram()
#ggplot(data = fbf, aes(x = friends)) + geom_histogram()
#ggplot(data = fbf, aes(x = gender)) + geom_bar()
#inference(y = gender, data = fbf, statistic = "proportion", type = "ci", method = "theoretical", success = "m")
#ggplot(fbf, aes(factor(people_in_pic), friends)) + geom_boxplot()
#summary(fbf)